#mybatis
mybatis:
  mapper-locations: classpath*:com/hmys/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true  #驼峰命名映射开关
#server
server:
  port: 80
#spring
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hm?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 111111
  freemarker:
    suffix: .html
    charset: utf-8
    content-type: text/html
    cache: false
    template-loader-path: classpath:/templates/
  profiles:
      active: dev   #指定读取配置文件:dev(开发环境),prod(生产环境),qa(测试环境)
#log
logging:
  config: classpath:logback-${spring.profiles.active}.xml
